package fr.gest.service;

import fr.gest.domain.Rpg;
import org.springframework.data.repository.Repository;

import java.util.Collection;

/**
 * This interface is a repository.
 * Each method correspond to a query on database.
 * The real query is generated by Spring Data JPA
 */
public interface RpgRepository extends Repository<Rpg, Long> {
  <S extends Rpg> S save(S entity);

  Rpg findOne(Long primaryKey);

  Collection<Rpg> findAll();
}
